# https://dev.azure.com/spyder-ide/spyder/

jobs:

################################################################################
# macOS
################################################################################
- job: 'macOS_Conda'

  pool:
    vmImage: 'macOS-10.13'

  variables:
    USE_CONDA: "yes"
    CI: True
    AZURE: True

  # Run the pipeline with multiple Python versions
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
    # Set the UsePythonVersion task to reference the matrix variable for its Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: sudo install -d -m 0777 /usr/local/miniconda/envs/
    displayName: Fix Conda permissions

    # Conda setup environment.
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/conda-environment?view=vsts
    #
  - task: CondaEnvironment@0
    inputs:
      environmentName: 'test'
      packageSpecs: 'python=$(python.version)'

    # Install dependencies
  - script: |
      ./continuous_integration/azure/install.sh
    displayName: 'Install dependencies'
    continueOnError: false

    # Show Conda Build Env
  - script: |
      echo "cwd:" `pwd`
      conda list | egrep -v '^#' | perl -ne 's/_/-/g; @x=split /\s+/, lc $_; print "$x[0]==$x[1]\n"' | sort | uniq
    displayName: 'Show build environment'
    continueOnError: true

    # Run Tests
  - script: |
      ./continuous_integration/azure/runtests.sh || ./continuous_integration/azure/runtests.sh || ./continuous_integration/azure/runtests.sh
    displayName: 'Run tests'
    continueOnError: false

    # Publish test results to the Azure DevOps server
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'result.xml'
      testRunTitle: 'Python $(python.version)'
      condition: succeededOrFailed()
